# Generated by Django 4.1.5 on 2023-01-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeks', '0002_participant_alter_sprint_description_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='percent',
            field=models.FloatField(default=0.0),
        ),
    ]
